with open("include/colors.h", "w") as f:
	f.write("// Auto-generated by gencolors.py. Do not edit!\n")
	f.write("\n")
	f.write("#ifndef _COLORS_H_\n")
	f.write("#define _COLORS_H_\n")
	f.write("\n")
	f.write("#include <stdint.h>\n")
	f.write("\n")
	f.write("const uint8_t bvs1_triad6_colors[] = {\n")
	for r in range(9):
		for g in range(9):
			for b in range(9):
				f.write(f"\t0x{int(r / 8 * 255):02x}, 0x{int(g / 8 * 255):02x}, 0x{int(b / 8 * 255):02x},\n")
	f.write("};\n")
	f.write("\n")
	f.write("#endif")